// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: HTServer.proto

package HTServerGrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type HTRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Imei    string `protobuf:"bytes,1,opt,name=imei,proto3" json:"imei,omitempty"`       //设备imei
	OprCode string `protobuf:"bytes,2,opt,name=oprCode,proto3" json:"oprCode,omitempty"` //指令编码
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`       //参数内容  一般为json数据 解析成功指定参数格式
}

func (x *HTRequest) Reset() {
	*x = HTRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HTServer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTRequest) ProtoMessage() {}

func (x *HTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_HTServer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTRequest.ProtoReflect.Descriptor instead.
func (*HTRequest) Descriptor() ([]byte, []int) {
	return file_HTServer_proto_rawDescGZIP(), []int{0}
}

func (x *HTRequest) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *HTRequest) GetOprCode() string {
	if x != nil {
		return x.OprCode
	}
	return ""
}

func (x *HTRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// The response message containing the greetings
type HTReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Imei     string `protobuf:"bytes,1,opt,name=imei,proto3" json:"imei,omitempty"`          //设备imei
	OprCode  string `protobuf:"bytes,2,opt,name=oprCode,proto3" json:"oprCode,omitempty"`    //指令编码
	RespCode int32  `protobuf:"varint,3,opt,name=respCode,proto3" json:"respCode,omitempty"` //错误代码
	Message  string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`    //提示信息
	Data     []byte `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`          //一般为json数据 解析成功指定参数格式
}

func (x *HTReply) Reset() {
	*x = HTReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_HTServer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTReply) ProtoMessage() {}

func (x *HTReply) ProtoReflect() protoreflect.Message {
	mi := &file_HTServer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTReply.ProtoReflect.Descriptor instead.
func (*HTReply) Descriptor() ([]byte, []int) {
	return file_HTServer_proto_rawDescGZIP(), []int{1}
}

func (x *HTReply) GetImei() string {
	if x != nil {
		return x.Imei
	}
	return ""
}

func (x *HTReply) GetOprCode() string {
	if x != nil {
		return x.OprCode
	}
	return ""
}

func (x *HTReply) GetRespCode() int32 {
	if x != nil {
		return x.RespCode
	}
	return 0
}

func (x *HTReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HTReply) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_HTServer_proto protoreflect.FileDescriptor

var file_HTServer_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x48, 0x54, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x0c, 0x48, 0x54, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x22, 0x4d,
	0x0a, 0x09, 0x48, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x69,
	0x6d, 0x65, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x12,
	0x18, 0x0a, 0x07, 0x6f, 0x70, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6f, 0x70, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x81, 0x01,
	0x0a, 0x07, 0x48, 0x54, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d, 0x65,
	0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6d, 0x65, 0x69, 0x12, 0x18, 0x0a,
	0x07, 0x6f, 0x70, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6f, 0x70, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x32, 0x56, 0x0a, 0x0f, 0x48, 0x54, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x43, 0x0a, 0x0f, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x48, 0x54,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x2e, 0x48, 0x54, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x48, 0x54, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x48, 0x54, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x2e,
	0x48, 0x54, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x6c, 0x0a, 0x1c, 0x4c, 0x52, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2e, 0x48, 0x54, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x42, 0x11, 0x48, 0x54, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x37,
	0x67, 0x69, 0x74, 0x65, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x6e, 0x75, 0x69, 0x62,
	0x69, 0x6e, 0x2f, 0x6c, 0x72, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2d, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x2d, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2f, 0x48, 0x54, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x47, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_HTServer_proto_rawDescOnce sync.Once
	file_HTServer_proto_rawDescData = file_HTServer_proto_rawDesc
)

func file_HTServer_proto_rawDescGZIP() []byte {
	file_HTServer_proto_rawDescOnce.Do(func() {
		file_HTServer_proto_rawDescData = protoimpl.X.CompressGZIP(file_HTServer_proto_rawDescData)
	})
	return file_HTServer_proto_rawDescData
}

var file_HTServer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_HTServer_proto_goTypes = []interface{}{
	(*HTRequest)(nil), // 0: HTServerGrpc.HTRequest
	(*HTReply)(nil),   // 1: HTServerGrpc.HTReply
}
var file_HTServer_proto_depIdxs = []int32{
	0, // 0: HTServerGrpc.HTServerService.HandleHTRequest:input_type -> HTServerGrpc.HTRequest
	1, // 1: HTServerGrpc.HTServerService.HandleHTRequest:output_type -> HTServerGrpc.HTReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_HTServer_proto_init() }
func file_HTServer_proto_init() {
	if File_HTServer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_HTServer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_HTServer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HTReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_HTServer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_HTServer_proto_goTypes,
		DependencyIndexes: file_HTServer_proto_depIdxs,
		MessageInfos:      file_HTServer_proto_msgTypes,
	}.Build()
	File_HTServer_proto = out.File
	file_HTServer_proto_rawDesc = nil
	file_HTServer_proto_goTypes = nil
	file_HTServer_proto_depIdxs = nil
}
